<?php
define('GROUPRELATION_YEAR', '2016');

function grouprelation_menu() {
  $items['group/search'] = array(
    'page callback' => 'grouprelation_search',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );
  $items['group/name/%'] = array(
    'page callback' => 'groupinfo_show',
    'access arguments' => array(
      'access content',
    ),
    'page arguments' => array(
      2,
    ),
    'type' => MENU_CALLBACK,
  );
  $items['group/fine_record/%'] = array(
    'page callback' => 'query_fine_record',
    'access arguments' => array(
      'access content',
    ),
    'page arguments' => array(
      2,
    ),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function find_group_json($group_name){
    $year = GROUPRELATION_YEAR;
    $json_base_path = 'companydata/group_relation/';
    $json_filename=$group_name.'_'.$year.'_list.json';
    $json_file = $json_base_path .$group_name.'/'.$json_filename;
    #$json_test = $json_base_path .$json_filename;

    drupal_add_js("var json_path = '".base_path().$json_file."';", 'inline');
    return $json_file;
}

function init_library(){
    $module_base_path = drupal_get_path('module', 'grouprelation');
    $plugin_base_path = $module_base_path."/plugin";
    $options = array(
        'scope' => 'footer',
        'type' => 'file',
    );
    
    drupal_add_css($plugin_base_path."/bootstrap/css/bootstrap.min.css", $options);
    drupal_add_css($module_base_path."/grouprelation.css", $options);
    drupal_add_js($plugin_base_path."/jQuery/jQuery-2.2.0.min.js", $options);
    drupal_add_js($plugin_base_path."/datatables/jquery.dataTables.min.js", $options);
    drupal_add_js($plugin_base_path."/datatables/dataTables.buttons.min.js", $options);
    drupal_add_js($plugin_base_path."/datatables/dataTables.bootstrap.min.js", $options);
    drupal_add_js($plugin_base_path."/d3/d3.v3.min.js", $options);
}

function init_custom(){
    $module_base_path = drupal_get_path('module', 'grouprelation');
    $js_base_path = $module_base_path."/js/";
    $options = array(
        'scope' => 'footer',
        'type' => 'file',
    );
    drupal_add_js($js_base_path."/init.js", $options);
    drupal_add_js($js_base_path."/group.js", $options);
    drupal_add_js($js_base_path."/graph.js", $options);
}

function groupinfo_show($group_name){
    //drupal_set_message(var_export($group_name, TRUE));
    init_library();
    init_custom();
  
    $json_file = find_group_json($group_name);
    if (is_file($json_file)) {
      $json = file_get_contents($json_file);
      $group_data = json_decode($json);
      if (!empty($group_data)) {
        // set page title
        drupal_set_title($group_data->company_summery->group_name. '集團');
        // we should use php to generate static data here for better SEO
        $summary = array(
          '集團公司總數' => $group_data->company_summery->company_amount.'家',
          '是否有裁罰記錄' => $group_data->company_summery->has_fine ? '是' : '否',
          '有裁罰記錄公司總數' => $group_data->company_summery->fine_company_amount . '家',
          '裁罰記錄總數' => $group_data->company_summery->fine_record_num.'次',
          '裁罰金額總數' => 'NTD $'.number_format($group_data->company_summery->fine_penalty_amount). ' 元',
        );
        $items = array();
        foreach($summary as $label => $s) {
          $items[] = "<label>{$label}:</label> <span>{$s}<span>";
        }

        $output = '';
        $output .= '<h2 class="group-data-title">集團基本資料</h2>';
        $output .= '<div id="table_summery_area" class="group-data-block">';
        $output .= '<div id="summery_content">';
        $output .= '<ul><li>'.implode('</li><li>', $items).'</li></ul>';
        $output .= '</div></div>';

        $graph_url = base_path().'companydata/graph.html?year='.GROUPRELATION_YEAR.'&group='.$group_name;
        $output .= '<h2 class="group-data-title">集團關係圖</h2>';
        $output .= '<div class="group-data-block">';
        $output .= '<iframe src="'.$graph_url.'" frameBorder="0" width="100%" height="480px" scrolling="no"></iframe>';
        $output .= '<a target="_blank" href="'.$graph_url.'"><i class="glyphicon glyphicon-stats"></i> 新視窗開啟</a>';
        $output .= '</div>';

        $output .= '<h2 class="group-data-title">子公司搜尋</h2>';
        $output .= '<div id="table_company_area" style="display: none" class="group-data-block">';
        $output .= '<table id="table_company" >';
        $output .= '<thead><tr>';
        $output .= '<th >子公司統一編號</th>';
        $output .= '<th >子公司名稱</th>';
        $output .= '<th >母公司列表</th>';
        $output .= '</tr></thead></table>';
        $output .= '</div>';

        $output .= '<h2 class="group-data-title">裁罰紀錄搜尋</h2>';
        $output .= '<div id="table_fine_company_area" style="display: none" class="group-data-block">';
        $output .= '<table id="table_fine_company">';
        $output .= '<thead><tr>';
        $output .= '<th >公司名稱</th>';
        $output .= '<th >統一編號</th>';
        $output .= '<th >裁罰記錄總數</th>';
        $output .= '<th >裁罰金額總數</th>';
        $output .= '</tr></thead></table>';
        $output .= '</div>';

        $output .= '<div id="table_fine_record_area" style="display: none" class="group-data-block">';
        $output .= '<table id="table_fine_record">';
        $output .= '<thead><tr>';
        $output .= '<th >工廠名稱</th>';
        $output .= '<th >裁罰日期</th>';
        $output .= '<th >裁罰金額</th>';
        $output .= '<th >違反法律</th>';
        $output .= '<th >是否請願</th>';
        $output .= '</tr></thead></table>';
        $output .= '</div>';

        return $output;
      }
    }
    drupal_not_found();
}

function query_belong_group($search_target, $search_type){
  $year = GROUPRELATION_YEAR;
  $query = "SELECT factory_group.group from factory_group";
  if($search_type=='source'){
    $query .= " where sublist_source like :search_target";
    $args = array(
        ':search_target' => '%'.db_like($search_target).'%',
        ':year'=>$year
    );
  }
  else if($search_type=='taxcode'){
    $query .= " where taxcode_source =:search_target";
    $args = array(
        ':search_target' => $search_target,
        ':year'=>$year
    );
  }
   else if($search_type=='stock'){
    $query .= " where stock =:search_target";
    $args = array(
        ':search_target' => $search_target,
        ':year'=>$year
    );
  }
  $query .= " and year=:year";
  $result = db_query($query, $args);
  $rows = array();
  foreach($result as $r) {
    array_push($rows, $r->group);
  }
  //drupal_set_message(var_export($year, TRUE));

  drupal_add_js("var group_name = ".json_encode($rows).";", 'inline');
}

function grouprelation_search(){
    $title = '集團搜尋';
    drupal_set_title($title);

    if ($_REQUEST['search_stock']!=''){
       $target=$_REQUEST['search_stock'];
       query_belong_group($target, 'stock');
    }  
    else if($_REQUEST['search_text']!=''){
      $target=$_REQUEST['search_text'];
      $new_target=str_replace("臺灣", "台灣", $target);
      query_belong_group($new_target, 'source');
    }
    else if ($_REQUEST['search_taxcode']!=''){
       $target=$_REQUEST['search_taxcode'];
       query_belong_group($new_target, 'taxcode');
    }  
    else{
      drupal_add_js("var group_name = 'all';", 'inline');
    }

    init_library();
    init_custom();

    $output = '<div class="group-search-wrapper">';
    $output .= '<div class="group-search-form">';
    $output .= '<form>';
    $output .= '<div class="form-item"><label for="search_text">集團或公司名稱</label><input id="search_text" name="search_text" type="text" class="form-text" /></div>';
    $output .= '<div class="form-item"><label for="search_stock">公司股票</label><input id="search_stock" name="search_stock" type="text" class="form-text" /></div>';
    $output .= '<div class="form-item"><label for="search_taxcode">公司統一編號</label><input id="search_taxcode" name="search_taxcode" type="text" class="form-text" /></div>';
    $output .= '<div class="form-item submit-buttons"><input type="submit" class="form-submit btn-4 rounded" value="查詢" /></div>';
    $output .= '</form>';
    $output .= '</div>';

    $output .= '<div id="table_group_list_area" style="display: none" class="group-search-list">';
    $output .= '<table id="table_group_list">';
    $output .= '</table>';
    $output .= '</div>';

    $output .= '<div class="group-search-list"><span id="search_warning" style="display: none">沒有符合的結果</span></div>';
    $output .= '</div><!--end group-search-wrapper-->';
    return $output;
}

function query_fine_record($taxcode){
    //if($_REQUEST['taxcode']!=''){
    //  $taxcode=$_REQUEST['taxcode'];

    $query = "SELECT factory_fine.facility_name, factory_fine.penalty_date, factory_fine.penalty_money, factory_fine.transgress_law, factory_fine.is_petition, factory_fine.petition_results, factory_corp.registration_no from factory_fine, factory_corp where factory_corp.corp_id=:taxcode and factory_corp.registration_no=factory_fine.registration_no";
    $args = array(
      ':taxcode' => $taxcode,
    );
    $result = db_query($query, $args);
    $rows = array();
    foreach($result as $r) {
      $row = array(
        'facility_name'=>$r->facility_name,
        'penalty_date'=>$r->penalty_date,
        'penalty_money'=>$r->penalty_money,
        'transgress_law'=>$r->transgress_law,
        'is_petition'=>$r->is_petition,
        'petition_results'=>$r->petition_results
      );
      array_push($rows, $row);
    }
    echo json_encode($rows);
    //}
    drupal_exit();
}

function grouprelation_index() {
  // set title
  $title = '集團搜尋';
  drupal_set_title($title);

  // prepare static file path
  $json_base_path = base_path().'/companydata/';
  $json_file_a = $path . 'test.json';

  // add js file to footer
  $module_base_path = drupal_get_path('module', 'grouprelation');
  $js_base_path = $module_base_path."/js/";
  $plugin_base_path = $muldie_base_path."/plugin/";

  $options = array(
    'scope' => 'footer',
    'type' => 'file',
  );
  drupal_add_js("$js_base_path/test.js", $options);

  // database query
  $query = "SELECT * FROM {factory_group} WHERE id = :id";
  $args = array(
    ':id' => 1,
  );
  $result = db_query($query, $args);
  $rows = array();
  foreach($result as $r) {
    $row = array(
      $r->id,
      $r->year,
      $r->group,
    );
    $rows[] = implode(',', $row);
  }

  // begin output
  $output = '';
  $output .= 'abc';
  $output .= '<a href="#">link</a>';
  $output .= '<div>'.implode('<br>', $rows).'</div>';

  // return to show output
  return $output;
}   
